### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ShalokShalom** [costajob/app-servers#21]
https://elixirforum.com/t/elixir-cowboy-benchmarks/8232

**Comment by allyraza** [comment]
I don't trust the results, in his benchmarks ruby is apparently faster then both elixir and pony to my surprise, Pony should out perform all the languages listed I ran similar benchmarks some time ago with pony out performing rust and go

**Comment by ShalokShalom** [comment]
@allyraza Did you test chapel also? Pony outperforming Go and Rust sounds also a bit confusing to me.
On par yes, while nobody can "outperform" near C performance, right? 
So its probably about the code.

**Comment by costajob** [comment]
Hi all, thanks for writing. 
I suggest you forking the repo and running the test on your workstation, then focusing on the implementation you want to squeeze performance out.
I am not an expert in all of the languages presented, i just relied on some examples i found online and tweaked with them. I definitively appreciate help from any external resources.
I will try out using wrk on a different device, but, again, the penalty should be reflected on all of the languages tested: if wrk would affect the performance so much i would expect to see similar results for all of the languages, bit this isn't the case.
Choosing a language over another is not just a matter of performance anyway, so if you are happy with Elixir/Pony i am not suggesting you they are bad languages at all.
The main scope for me is also testing how easy is to implement a HTTP server with standard/external libraries, and i've got an idea ;)
Closing this issue, because, well, lack of faith is not an issue at all ;)
Regards

**Comment by ShalokShalom** [comment]
You benchmark the power of the language, to perform `Hello World` which is tiny part of a language.

**Comment by costajob** [comment]
Again the "power" of a language does not reside on its performance. 
Here i am just doing a micro-bench. You can check more complicated bench on [TechEmpower](https://www.techempower.com/benchmarks/) site.

**Comment by ShalokShalom** [comment]
The results are misleading.

**Comment by costajob** [comment]
Then fork the repo and post your findings ;)
That's pretty interesting anyway, since these micro-bench were inspired by [some tests](https://github.com/mroth/phoenix-showdown) born in the Elixir world as an extension to the [original ones](https://littlelines.com/blog/2014/07/08/elixir-vs-ruby-showdown-phoenix-vs-rails) made by Phoenix's author: both these benchmarks used `wrk` as the stress tool on the same workstation running the server.
The same tests were even mentioned in the Pragmatic Programmer's Book [Programming Phoenix](https://pragprog.com/book/phoenix/programming-phoenix) (pag. 2), a great book by the way.
Regarding Elixir slowness on these tests: i was surprised too, ran `wrk` several times (warming up BEAM much more than , say, JVM), but these are the numbers that i've got from two different MacBook PRO. 
Again you should not choose a language basing on such tests, they just serves the scope, for me, to understand how different languages deals with HTPP server implementation by using standard libraries. 
Anyway any opinions is very welcome, i just appreciate more the constructive ones ;)
Regards

**Comment by costajob** [comment]
Just preparing new benchmark with WRK running on a separate server, you can find results on a feature repo.
I will merge them with master soon.

**Comment by ShalokShalom** [comment]
Do you prefer WRK for a specific reason?

**Comment by costajob** [comment]
I've just seen many of the bechmark done in the Ruby world rely on WRK. Do you suggest using WRK2? Is it much better?

**Comment by ShalokShalom** [comment]
Its different from casual WRK: https://elixirforum.com/t/elixir-cowboy-benchmarks/8232/4

**Comment by costajob** [comment]
I read it. 
I will retry the benchmarks against wrk2, although you can see the position by throughput is more or less the same than previous version (but for NIM, which now outperforms all the others). 
I also cannot get some decent numbers from Ruby's Puma anymore, so switched to Passenger.
I also removed Pony, since the throughput is very bad i suspect the example i copied misses something.

Thanks

**Comment by ShalokShalom** [comment]
> although you can see the position by throughput is more or less the same than previous version (but for NIM, which now outperforms all the others).

Yeah, and when you change the code into some other use case, will this change dramatically again maybe?

> I also removed Pony, since the throughput is very bad i suspect the example i copied misses something.

You can talk with their devs, their are very nice.

**Comment by costajob** [comment]
I will, thanks.

**Comment by costajob** [comment]
Tried to bench with WRK2, but missed the point: it is aimed to record better latency, but it does this by limiting throughput.
When throughput is not  limited (using a large number), the values are identical to the original WRK (on which WRK2 heavily relies), and latency numbers equals the test duration (~30s).
I will reserve to use it for latency recording, but in this particular micro-benchmark (i am testing "hello world" after all) i suppose it is not the right tool.
Thanks anyway for your suggestions.

**Comment by ShalokShalom** [comment]
Nice to know. Thanks
