### ISSUE TITLE
Dart2Native benchmark

### ISSUE THREAD

**Issue by ansarizafar** [costajob/app-servers#35]
Dart2Native is released. Please update your benchmark and use Dart2Native in place of Dart VM

**Comment by costajob** [comment]
Hi, by using `dart2aot` i already used the AOT compilation, but i assume using `dart2native` is more correct nonetheless.
Throughput also gained something.
Thanks

**Comment by ansarizafar** [comment]
> Throughput also gained something.

Could you please share How much throughput, Memory/Cpu consumption changed when using dart2native?

**Comment by costajob** [comment]
I've updated the [numbers](https://github.com/costajob/app-servers/commit/e3aad3477282f01ec24fbc7391e17a0efe669fa2) accordingly.

It's difficult to say if it depends on dart2native, since as i said i already used `dartaotruntime`to execute AOT complied code. Memory consumption is essentially the same.

**Comment by ansarizafar** [comment]
Thanks
