### ISSUE TITLE
Things to improve

### ISSUE THREAD

**Issue by nono** [costajob/app-servers#5]
Hello,

I think there are some things to improve this benchmark:

- First, the payload for the Elixir version is `Hello world!` (12 bytes), but the payload for other tests is `Hello world` (11 byte). Not a big deal ;-)

- Then, on the same topic, seeing the Transfer/sec is interesting. It looks like Node and Elixir are sending heavier HTTP headers than Ruby and Go for example.

- For Elixir, I think it should be more fair to use [the Hello World example from Plug](https://github.com/elixir-lang/plug#hello-world) instead of a router. Others don't have a router.

- Last but not least, http pipelining should be disabled for all tests. See https://github.com/wg/wrk/issues/197 for some details.

**Comment by costajob** [comment]
Thanks for suggestions, i will apply them on next commits and make a new bench run!

**Comment by costajob** [comment]
Regarding Elixir: i initially used Plug as described by Plug README, but i am not aware how to run the server on prod mode without using the iex (as in the README).
By using a full router i am able to run it with mix and get some more throughput.
If you have any suggestions how to run elixir plug via mix i'll be glad to refactor.

**Comment by costajob** [comment]
Hi,

i've applied some of your suggestions ;)

Regarding the Plug one i've not been able to find how to start a simple plug by mix: that's a pity but i fear the documentation is not always clear here.
I will left the router version since i can start the server by mix on prod mode and get some better 
throughput from it.

Regarding disabling HTTP pipelining: by disabling it i get more or less the same throughput from all app servers (~500 req/sec). 
I fear that the limit here is reached by wrk coupled with my network interface. 
Since i saw others does test without closing the connection on each request, i will leave old (keep-alive) configuration. ;)
